# Configs for Github actions
# on: Github actions run ON push
# jobs: runs-on: runner (operating system) we run our jobs on
# Steps: uses: use another pre-made action step up to perform a specific task
# then passing in parameters so you can login to docker
# Checkout is action that checks code out in github actions job
# Finally, we run unit test on the project and then run Lint
---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
